### PR TITLE
Pull 1.9 images

### PR DESCRIPTION
**Pull request by ojongerius**
No need to use an old version of Go, AFAICS.

### CODE REVIEW

**Comment by drasko** [comment]
@ojongerius +1 for 1.9, but Canonical guys requested 1.8 I think, and this is what Jim put on the Wiki.

Can you please start a thread on ML just to double-check if everybody is OK for 1.9 before I merge this one?

**Comment by ojongerius** [comment]
Sure, which mailinglist woud that be, edgex-golang?

**Comment by drasko** [comment]
Yes, and I think edgex-develop would do also

**Comment by drasko** [comment]
@ojongerius can you please re-post this question on project's ML so we can move with this PR?

**Comment by drasko** [comment]
Let's close this one for now, re-opening it when community decides to bump Go version.

**Pull request closed without merging**
